name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build plugin
      run: npm run build
      
    - name: Create plugin directory
      run: mkdir obsidotion-plugin
      
    - name: Copy plugin files
      run: |
        cp main.js obsidotion-plugin/
        cp manifest.json obsidotion-plugin/
        cp styles.css obsidotion-plugin/
        
    - name: Create zip
      run: cd obsidotion-plugin && zip -r ../obsidotion-plugin.zip . && cd ..
      
    - name: Upload release asset
      uses: actions/upload-artifact@v4
      with:
        name: obsidotion-plugin
        path: obsidotion-plugin.zip
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: obsidotion-plugin.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 